version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-express
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_DBNAME=mydbname

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
     - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/ 
